var dadosCheckup = [
  {
    "Hemograma": "Anemia ",
    "Glicemia": "121 mg/dL",
    "Colesterol": "197 mg/dl",
    "Triglicerideos": "200 mg",
    "Ureia": "47 mg/ dL",
    "Creatina": "1,3 mg/dL",
    "tgo": "49 U/L",
    "tgp": "59 U/L",
    "TSH": "4,0 (?UI/mL)",
    "t4": "3,8 ng/dl",
    "acido": "7,8 mg/dl",
    "Eletrocardiograma": "110 bpm",
    "ergometrico": "Pressão alterada",
    "Ecocardiograma": "Alterado",
    "Estado": "grave",
    "Email": "josesilva@contoso.com"
  },
  {
    "Hemograma": "Normal ",
    "Glicemia": "101 mg/dL",
    "Colesterol": "163 mg/dl",
    "Triglicerideos": "133 mg",
    "Ureia": "32 mg/ dL",
    "Creatina": "1,1 mg/dL",
    "tgo": "29 U/L",
    "tgp": "24 U/L",
    "TSH": "3,1 (?UI/mL)",
    "t4": "1,2 ng/dl",
    "acido": "5,2 mg/dl",
    "Eletrocardiograma": "92 bpm",
    "ergometrico": "Pressão anormal",
    "Ecocardiograma": "Anormal",
    "Estado": "anormal",
    "Email": "andrenascimento@contoso.com"
  },
  {
    "Hemograma": "Normal ",
    "Glicemia": "85 mg/dL",
    "Colesterol": "142 mg/dl",
    "Triglicerideos": "123 mg",
    "Ureia": "25 mg/ dL",
    "Creatina": "0,8 mg/dL",
    "tgo": "13 U/L",
    "tgp": "15 U/L",
    "TSH": "1,6 (?UI/mL)",
    "t4": "0,8 ng/dl",
    "acido": "3,1 mg/dl",
    "Eletrocardiograma": "75 bpm",
    "ergometrico": "Pressão normal",
    "Ecocardiograma": "Normal",
    "Estado": "normal",
    "Email": "julianasouza@contoso.com"
  }
];